[[redirects]]
  from = "/proxy-obras"
  to = "PEGA-AQUÍ-EL-ENLACE-DE-LA-PESTAÑA-OBRAS"
  status = 200
  force = true

[[headers]]
  for = "/proxy-obras"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "text/csv; charset=utf-8"